name: release
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for release'
        required: true
        type: string

jobs:
  build:
    uses: saigai-studios/saigai-solves/.github/workflows/build.yml@main
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Repository
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4

    - name: Display filesystem contents
      run: ls -R

    - name: Rename downloads
      run: |
        mv ./saigai-solves-macos-x64/SaigaiSolves.tar ./saigai-solves-macos-x64-${{ inputs.version }}.tar
        mv ./saigai-solves-ubuntu-x64/SaigaiSolves.tar ./saigai-solves-ubuntu-x64-${{ inputs.version }}.tar
        mv ./saigai-solves-webgl/SaigaiSolves.tar ./saigai-solves-webgl-${{ inputs.version }}.tar
        mv ./saigai-solves-windows-x64/SaigaiSolves.tar ./saigai-solves-windows-x64-${{ inputs.version }}.tar

    - name: Validate release notes
      run: .github/workflows/autocl.py ${{ inputs.version }}

    - name: Write release notes
      run: echo "$(.github/workflows/autocl.py ${{ inputs.version }})" > ./RELEASE_NOTES.md

    - name: Tag commit as version
      run: git tag ${{ inputs.version }}

    - name: Push specific version tag
      run: git push --tags
      
    - name: Upload releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: './saigai-solves-*.tar'
        bodyFile: ./RELEASE_NOTES.md
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}